import FeatureCard from "./FeatureCard";

const Features = () => {
  const features = [
    {
      icon: "🎥",
      title: "AI Mock Interviews",
      description: "Role-specific questions generated by AI."
    },
    {
      icon: "📊",
      title: "Performance Analysis",
      description: "Get detailed insights on communication and confidence."
    },
    {
      icon: "💬",
      title: "Answer Evaluation",
      description: "AI evaluates relevance, depth and clarity."
    },
    {
      icon: "📄",
      title: "Resume Matching",
      description: "Match your resume with the target role."
    },
    {
      icon: "▶️",
      title: "Interview Replay",
      description: "Review your interview and improve."
    },
    {
      icon: "📥",
      title: "Detailed Reports",
      description: "Download recruiter-style reports."
    }
  ];

  return (
    <section className="features-section">

      <div className="features-header">
        <p>FEATURES</p>
        <h2>Everything You Need to Ace Your Interviews</h2>
      </div>

      <div className="features-grid">
        {features.map((feature, index) => (
          <FeatureCard
            key={index}
            title={feature.title}
            description={feature.description}
            icon={feature.icon}
          />
        ))}
      </div>

    </section>
  );
};

export default Features;